#!/bin/sh

trap "echo TRAPed signal" HUP INT QUIT TERM

#/usr/sbin/postconf -e inet_interfaces=all
/usr/sbin/postfix start

echo "[hit enter key to exit] or run 'docker stop <container>'"
read

echo "stopping postfix"
/usr/sbin/postfix stop

echo "exited $0"
